DROP    SEQUENCE PROJECT_CREATENOSEQ;
CREATE  SEQUENCE PROJECT_CREATENOSEQ;

CREATE TABLE PROJECT_CREATE(
    PROJECT_CREATENO    NUMBER PRIMARY KEY
    ,USERNO             NUMBER NOT NULL
    ,PROJECTNO          NUMBER NOT NULL
,CONSTRAINT PC_FK_USERNO    FOREIGN KEY(USERNO)     REFERENCES USERINFO(USERNO)
,CONSTRAINT PC_FK_PROJECTNO FOREIGN KEY(PROJECTNO) REFERENCES PROJECT(PROJECTNO)
);