DROP    SEQUENCE PROJECTNOSEQ;
CREATE  SEQUENCE PROJECTNOSEQ;

DROP TABLE PROJECT;
CREATE TABLE PROJECT (
    PROJECTNO       NUMBER          NOT NULL
    ,PROJECTNAME    VARCHAR2(20)    NOT NULL
    ,PROJECTURL     VARCHAR2(200)
,CONSTRAINT PROJECT_PK PRIMARY KEY(PROJECTNO));
);