--테이블 구조는 공유폴더 내 테이블정의서 or www.erdcloud.com/d/t6xePAoBokaZXd6Ym 참조
--!!!!테이블 구조 수정시 1.ERDcloud / 2.SQL문 / 3.08논리물리ERD/ 4.09테이블정의서 모두 업데이트 해줘야됌...!!

--순서.테이블이름 (속성갯수)

DROP TABLE TODO;
DROP TABLE TEXT;
DROP TABLE CHANNEL_CREATE;
DROP TABLE BOARD;
DROP TABLE PROJECT_CREATE;
DROP TABLE USERINFO;
DROP TABLE PROJECT;
DROP TABLE MAPS;
DROP TABLE FILES;
DROP TABLE CHANNEL;

--1.회원정보 테이블 (8)
DROP 	SEQUENCE USERNOSEQ;
CREATE 	SEQUENCE USERNOSEQ;
CREATE TABLE USERINFO(
	USERNO 			NUMBER 			PRIMARY KEY
	,USEREMAIL 		VARCHAR2(50) 	NOT NULL
	,USERPW 		VARCHAR2(100) 	NOT NULL
	,USERNAME 		VARCHAR2(20)	NOT NULL
	,USERGENDER 	VARCHAR2(1)
	,USERENABLED 	VARCHAR2(1) 	NOT NULL
	,USERROLE 		VARCHAR2(20) 	NOT NULL
	,USERURL 		VARCHAR2(3000)
,CONSTRAINT U_USERGENDER_CK 	CHECK (USERGENDER IN('M', 'W'))
,CONSTRAINT U_USERENABLED_CK 	CHECK (USERENABLED IN('Y', 'N'))
);

--2.프로젝트 테이블 (3)
DROP 	SEQUENCE PROJECTNOSEQ;
CREATE 	SEQUENCE PROJECTNOSEQ;
DROP TABLE PROJECT;
CREATE TABLE PROJECT (
    PROJECTNO   	NUMBER  		NOT NULL
    ,PROJECTNAME 	VARCHAR2(20) 	NOT NULL
    ,PROJECTURL 	VARCHAR2(200)
,CONSTRAINT P_PK PRIMARY KEY(PROJECTNO)
);

--3.프로젝트참여 테이블 (3)
DROP 	SEQUENCE PROJECT_CREATENOSEQ;
CREATE 	SEQUENCE PROJECT_CREATENOSEQ;
CREATE TABLE PROJECT_CREATE(
	PROJECT_CREATENO 	NUMBER PRIMARY KEY
	,USERNO 			NUMBER NOT NULL
	,PROJECTNO 			NUMBER NOT NULL
,CONSTRAINT PC_FK_USERNO 	FOREIGN KEY(USERNO) 	REFERENCES USERINFO(USERNO)
,CONSTRAINT PC_FK_PROJECTNO FOREIGN KEY(PROJECTNO) REFERENCES PROJECT(PROJECTNO)
);

--4.채널 테이블 (4)
DROP 	SEQUENCE CHANNELNOSEQ;
CREATE 	SEQUENCE CHANNELNOSEQ;
CREATE TABLE CHANNEL(
	CHANNELNO 		NUMBER 			PRIMARY KEY
	,CHANNELNAME 	VARCHAR2(30)
	,CHANNELTIME 	DATE
	,CHANNELSTATUS 	VARCHAR2(10)
);

--5.지도 테이블 (3)
DROP 	SEQUENCE MAPNOSEQ;
CREATE 	SEQUENCE MAPNOSEQ;
CREATE TABLE MAPS(
	MAPNO 		NUMBER 		PRIMARY KEY
	,LATITUDE 	NUMBER 		NOT NULL
	,LONGITUDE 	NUMBER 		NOT NULL
);

--6.파일 테이블 (3)
DROP 	SEQUENCE FILENOSEQ;
CREATE 	SEQUENCE FILENOSEQ;
CREATE TABLE FILES(
	FILENO 		NUMBER 			PRIMARY KEY
	,FILESTREAM VARCHAR2(3000) 	NOT NULL
	,FILETITLE 	VARCHAR2(30) 	NOT NULL
);

--7.게시글 테이블 (9)
DROP 	SEQUENCE BOARDNOSEQ;
CREATE 	SEQUENCE BOARDNOSEQ;
DROP 	SEQUENCE ANSWERSQSEQ;
CREATE 	SEQUENCE ANSWERSQSEQ;
CREATE TABLE BOARD(
	BOARDNO 		NUMBER 			PRIMARY KEY
	,USERNO 		NUMBER
	,PROJECTNO 		NUMBER 			NOT NULL
	,BOARDTITLE 	VARCHAR2(100)
	,BOARDCONTENT 	VARCHAR2(3000)
	,DELFLAG 		VARCHAR2(1)
	,REGDATE 		DATE 			NOT NULL
	,MAPNO 			NUMBER
	,FILENO 		NUMBER
,CONSTRAINT B_FK_USERNO 	FOREIGN KEY(USERNO) 	REFERENCES USERINFO(USERNO)
,CONSTRAINT B_FK_PROJECTNO 	FOREIGN KEY(PROJECTNO) 	REFERENCES PROJECT(PROJECTNO)
,CONSTRAINT B_DELFLAG_CK 	CHECK (DELFLAG IN('Y', 'N'))
,CONSTRAINT B_FK_MAPNO 		FOREIGN KEY(MAPNO) 		REFERENCES MAPS(MAPNO) 		ON DELETE CASCADE
,CONSTRAINT B_FK_FILENO 	FOREIGN KEY(FILENO) 	REFERENCES FILES(FILENO) 	ON DELETE CASCADE
);
--8.채팅 텍스트 테이블 (9)
DROP 	SEQUENCE TEXTNOSEQ;
CREATE 	SEQUENCE TEXTNOSEQ;
CREATE TABLE TEXT(
	TEXTNO 			NUMBER 			PRIMARY KEY
	,USERNO 		NUMBER 			NOT NULL
	,CHANNELNO 		NUMBER 			NOT NULL
	,ANSWERSQ 		NUMBER 			NOT NULL
	,TEXTCONTENT 	VARCHAR2(3000)
	,TEXTIP 		VARCHAR2(50) 	NOT NULL
	,TEXTTIME 		DATE 			NOT NULL
	,MAPNO 			NUMBER
	,FILENO 		NUMBER
,CONSTRAINT T_FK_USERNO 	FOREIGN KEY(USERNO) 	REFERENCES USERINFO(USERNO)
,CONSTRAINT T_FK_CHANNELNO 	FOREIGN KEY(CHANNELNO) 	REFERENCES CHANNEL(CHANNELNO)
,CONSTRAINT T_FK_MAPNO 		FOREIGN KEY(MAPNO) 		REFERENCES MAPS(MAPNO) 		ON DELETE CASCADE
,CONSTRAINT T_FK_FILENO 	FOREIGN KEY(FILENO) 	REFERENCES FILES(FILENO) 	ON DELETE CASCADE
);
--9.채팅참여 테이블 (4)
DROP 	SEQUENCE CHANNEL_CREATENOSEQ;
CREATE 	SEQUENCE CHANNEL_CREATENOSEQ;
CREATE TABLE CHANNEL_CREATE(
	CHANNEL_CREATENO 	NUMBER PRIMARY KEY
	,USERNO 			NUMBER NOT NULL
	,CHANNELNO 			NUMBER NOT NULL
	,PROJECTNO 			NUMBER NOT NULL
,CONSTRAINT CC_FK_USERNO 	FOREIGN KEY(USERNO) 	REFERENCES USERINFO(USERNO)
,CONSTRAINT CC_FK_CHANELNO 	FOREIGN KEY(CHANNELNO) 	REFERENCES CHANNEL(CHANNELNO)
,CONSTRAINT CC_FK_PROJECTNO FOREIGN KEY(PROJECTNO) 	REFERENCES PROJECT(PROJECTNO)
);
--10.일정 테이블 (7)
DROP 	SEQUENCE TODOSEQ;
CREATE 	SEQUENCE TODOSEQ;
CREATE TABLE TODO(
	TODONO 			NUMBER 			PRIMARY KEY
	,PROJECTNO 		NUMBER 			NOT NULL
	,USERNO 		NUMBER 			NOT NULL
	,TODOTITLE 		VARCHAR2(4000) 	NOT NULL
	,TODOCONTENT 	VARCHAR2(4000)
	,TODODATE 		VARCHAR2(12)
	,TODOREGDATE 	DATE 			NOT NULL
,CONSTRAINT TD_FK_USERNO 	FOREIGN KEY(USERNO) 	REFERENCES USERINFO(USERNO)
,CONSTRAINT TD_FK_PROJECTNO FOREIGN KEY(PROJECTNO) 	REFERENCES PROJECT(PROJECTNO)
);

--테스트용 INSERT 구문들. 테스트 데이터가 필요시 넣으면 된다.
--시퀀스는 잘못 실행시 2 이후의 번호로 시작되므로 유의.
--FK유의. 만일 일부구문만 사용할 생각이라면 
--다른 테이블에 선행 입력되어야 하는 데이터를 파악 후 사용하자.

--프로젝트
INSERT INTO PROJECT
VALUES(
	PROJECTNOSEQ.NEXTVAL
	,'expjname'
	,'expjtitle');

--유저정보
INSERT INTO USERINFO(USERNO,USEREMAIL ,USERPW ,USERNAME ,USERGENDER ,USERENABLED ,USERROLE ,USERURL)
VALUES( 
	USERNOSEQ.NEXTVAL 
	,'ex@ex.com'
	,'expw' 
	,'exname'
	,'M'
	,'Y'
	,'ADMIN'
	, 1);
	
--프로젝트참여
INSERT INTO PROJECT_CREATE(PROJECT_CREATENO ,USERNO ,PROJECTNO)
VALUES (
	PROJECT_CREATENOSEQ.NEXTVAL 
	,1
	,1);
	
--채널
INSERT INTO CHANNEL(CHANNELNO, CHANNERNAME, CHANNELSTATUS, CHANNELTIME)
VALUES(
	CHANNELNOSEQ.NEXTVAL 
	,'exchname'
	,'exchstatus'
	,'20190117');
	
--지도
INSERT INTO MAPS(MAPNO, LATITUDE, LONGITUDE)
VALUES(
	MAPNOSEQ.NEXTVAL
	,192
	,192);
	
--파일
INSERT INTO FILES(FILENO, FILESTREAM, FILETITLE)
VALUES(
	FILENOSEQ.NEXTVAL
	,'c://notexist.jpg'
	,'exfltitle');
	
--게시글
INSERT INTO BOARD(BOARDNO, USERNO, PROJECTNO, BOARDTITLE, BOARDCONTENT
				,DELFLAG,REGDATE, MAPNO, FILENO)
VALUES(
	BOARDNOSEQ.NEXTVAL
	,1
	,1
	,'excttitle'
	,'exctcontent'
	,'N'
	,'20190117'
	,1
	,1);
