DROP    SEQUENCE TEXTNOSEQ;
CREATE  SEQUENCE TEXTNOSEQ;

CREATE TABLE TEXT(
    TEXTNO          NUMBER          PRIMARY KEY
    ,USERNO         NUMBER          NOT NULL
    ,CHANNELNO      NUMBER          NOT NULL
    ,ANSWERSQ       NUMBER          NOT NULL
    ,TEXTCONTENT    VARCHAR2(3000)
    ,TEXTIP         VARCHAR2(50)    
    ,TEXTTIME       DATE            NOT NULL
    ,MAPNO          NUMBER
    ,FILENO         NUMBER
,CONSTRAINT TT_FK_USERNO    FOREIGN KEY(USERNO)     REFERENCES USERINFO(USERNO)
,CONSTRAINT TT_FK_CHANNERNO FOREIGN KEY(CHANNELNO)  REFERENCES CHANNEL(CHANNELNO)
,CONSTRAINT TT_FK_MAPNO     FOREIGN KEY(MAPNO)      REFERENCES MAP(MAPNO)   ON DELETE CASCADE
,CONSTRAINT TT_FK_FILEN0O   FOREIGN KEY(FILENO)     REFERENCES FILE(FILENO) ON DELETE CASCADE
);