DROP    SEQUENCE USERNOSEQ;
CREATE  SEQUENCE USERNOSEQ;

CREATE TABLE USERINFO(
    USERNO          NUMBER          PRIMARY KEY
    ,USEREMAIL      VARCHAR2(50)    NOT NULL
    ,USERPW         VARCHAR2(100)   NOT NULL
    ,USERNAME       VARCHAR2(20)    NOT NULL
    ,USERGENDER     VARCHAR2(1)
    ,USERENABLED    VARCHAR2(1)     NOT NULL
    ,USERROLE       VARCHAR2(20)    NOT NULL
    ,USERURL        VARCHAR2(3000)
,CONSTRAINT UI_USERGENDER_CK    CHECK (USERGENDER IN('M', 'W'))
,CONSTRAINT UI_USERENABLED_CK   CHECK (USERENABLED IN('Y', 'N'))
);